In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Original Array:")
print(a)

print("First Row:")
print(a[0, :])

print("Second Column:")
print(a[:, 1])

print("First 2 Rows and First 2 Columns:")
print(a[0:2, 0:2])

print("Last 2 Rows and Last 2 Columns:")
print(a[1:3, 1:3])

Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
First Row:
[1 2 3]
Second Column:
[2 5 8]
First 2 Rows and First 2 Columns:
[[1 2]
 [4 5]]
Last 2 Rows and Last 2 Columns:
[[5 6]
 [8 9]]
